Replace FileHelper::filterPath to PathMatcher
yiisoft/files pull request #22
Opened 2020-11-08 15:11 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | #20

2020-11-13 21:23 UTC, samdark requested changes
Overall great idea.

2020-11-13 21:23 UTC, samdark commented on src/FileHelper.php
> +     * - filter: PathMatchInterface
```suggestion
     * - filter: PathMatcherInterface
```

2020-11-13 21:23 UTC, samdark commented on src/PathMatch/PathMatcherInterface.php
> +     * Checks if the passed path would matched.
```suggestion
     * Checks if the path matches.
```

2020-11-13 21:23 UTC, samdark commented on src/PathMatch/PathMatcherInterface.php
> +interface PathMatcherInterface
Need description.

2020-11-13 21:23 UTC, samdark commented on src/PathMatch/PathMatcher.php
> +final class PathMatcher implements PathMatcherInterface
Need description.

2020-11-16 19:47 UTC, vjik commented
`CsrfToken::getValue()` used to get token for send via request. Missing token should throw an exception, not generate a new token.

2020-11-20 12:10 UTC, rustamwin commented on src/PathMatch/PathMatcher.php
> +namespace Yiisoft\Files\PathMatch;
```suggestion
namespace Yiisoft\Files\Matcher;
```
It would be better :)

2020-11-20 12:10 UTC, rustamwin commented on src/PathMatch/PathMatcherInterface.php
> +namespace Yiisoft\Files\PathMatch;
```suggestion
namespace Yiisoft\Files\Matcher;
```
It would be better :)

2020-11-21 05:19 UTC, vjik commented on src/PathMatch/PathMatcher.php
> +namespace Yiisoft\Files\PathMatch;
Or `Yiisoft\Files\PathMatcher`?

2020-11-22 15:04 UTC, rustamwin commented on src/PathMatch/PathMatcher.php
> +namespace Yiisoft\Files\PathMatch;
I'm ok.

2020-11-22 15:16 UTC, vjik commented on src/PathMatch/PathMatcher.php
> +namespace Yiisoft\Files\PathMatch;
Done.

2020-11-22 21:57 UTC, samdark approved these changes

2020-11-22 22:01 UTC, samdark commented
This pull request seems to be alright but usage should be checked/adjusted in assets package, AssetPublisher.

2020-11-23 17:29 UTC, vjik commented
> This pull request seems to be alright but usage should be checked/adjusted in assets package, AssetPublisher.

Done: https://github.com/yiisoft/assets/pull/48

2020-11-23 20:39 UTC, merged

2020-11-23 20:39 UTC, samdark commented
Good one. Thank you!