Add methods FileHelper::findDirectories() and FileHelper::findFiles() + fix unlink broken symlinks in windows
yiisoft/files pull request #39
Opened 2020-12-16 21:18 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #13 

- Add `FileHelper::findDirectories()`
- Add `FileHelper::findFiles()`
- Fixed: in windows throws error on remove symlink to not exists dir via `FileHelper::unlink()`.

"Make recursive filtering really recursive" (#13) implemented in `findDirectories()`, but not in `copyDirectory`. I think this is right: if I except parent directory, then not need copy children files and directories.

2020-12-17 22:50 UTC, samdark commented on src/FileHelper.php
> +     * @return string[] directories found under the directory, in no particular order.
```suggestion
     * @return string[] directories found under the directory specified, in no particular order.
```

2020-12-17 22:50 UTC, samdark commented on src/FileHelper.php
> +            throw new InvalidArgumentException("The \"directory\" argument must be a directory: $directory");
```suggestion
            throw new InvalidArgumentException("\"$directory\" is not a directory.");
```

2020-12-19 10:51 UTC, vjik commented on src/FileHelper.php
> +            throw new InvalidArgumentException("The \"directory\" argument must be a directory: $directory");
Done.

2020-12-19 10:51 UTC, vjik commented on src/FileHelper.php
> +     * @return string[] directories found under the directory, in no particular order.
Done.

2020-12-19 10:51 UTC, vjik commented on src/FileHelper.php
> +            try {
Done.

2020-12-19 13:08 UTC, samdark requested changes

2020-12-19 13:08 UTC, samdark commented on README.md
> +### Workinkg with directories
```suggestion
### Working with directories
```

2020-12-19 13:08 UTC, samdark commented on src/FileHelper.php
> +                @rmdir($path);
```suggestion
                rmdir($path);
```

Because we don't want to stay silent in case it's windows and we fail to unlink.

2020-12-19 13:09 UTC, samdark approved these changes

2020-12-19 13:12 UTC, merged

2020-12-19 13:12 UTC, samdark commented
Awesome!